version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: actions-test-vite
    working_dir: /app
    volumes:
      - ./vue-project:/app
    ports:
      - "5173:5173"
