name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        default: staging
        options:
          - production
          - staging
      keyword:
        type: choice
        required: true
        default: apple
        options:
          - apple
          - banana
          - cherry
          - dekopon

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.keyword }}!

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
