name: CD staging

env:
  KEYWORD: ${{ inputs.keyword }}

on:
  workflow_dispatch:
    inputs:
      keyword:
        type: choice
        description: keyword
        required: true
        default: cherry
        options:
          - cherry
          - dekopon

jobs:
  build-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  build-fruit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.keyword }}!

  check-deploy:
    needs: [build-hello, build-fruit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check keyword
        run: bash validate-keyword-staging.sh

  deploy-hello:
    needs: [check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging-hello
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ toJson(github.event.commits) }}
          echo $KEYWORD

  deploy-fruit:
    needs: [check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging-fruit
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy ${{ inputs.keyword }}.
