name: CD staging

env:
  KEYWORD: ${{ inputs.keyword }}
  REF_NAME: ${{ github.ref_name }}
  COMMIT_SHA: ${{ github.sha }}
  EVENT_SOURCE: ${{ github.event_name }}
  USER_ID: ${{ github.actor_id }}
  USER: ${{ github.actor }}
  URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

on:
  workflow_dispatch:
    inputs:
      keyword:
        type: choice
        description: keyword
        required: true
        default: cherry
        options:
          - cherry
          - dekopon

jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_MESSAGE: ${{ steps.set_up_commit_message.outputs.COMMIT_MESSAGE }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Up environment Variables
        id: set_up_commit_message
        run: |
          echo "$(git show -s --format=%s)"
          echo "COMMIT_MESSAGE=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"

  build-hello:
    needs: [preprocess]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  build-fruit:
    needs: [preprocess]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ inputs.keyword }}!

  check-deploy:
    needs: [build-hello, build-fruit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check keyword
        run: bash validate-keyword-staging.sh

  deploy-hello:
    needs: [preprocess, check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging-hello
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ needs.preprocess.outputs.COMMIT_MESSAGE }}
          echo $KEYWORD
          echo $REF_NAME
          echo $COMMIT_SHA
          echo $EVENT_SOURCE
          echo $USER_ID
          echo $USER
          echo $URL
          echo "${${{ github.repository }}#${{ github.repository_owner }}/}"

  deploy-fruit:
    needs: [preprocess, check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging-fruit
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy ${{ inputs.keyword }}.
