name: CI production

on:
  workflow_dispatch:
    inputs:
      keyword:
        type: choice
        required: true
        default: apple
        options:
          - apple
          - banana

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.keyword }}!

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
