name: CI staging

on:
  workflow_dispatch:
    inputs:
      keyword:
        type: choice
        required: true
        default: cherry
        options:
          - cherry
          - dekopon

jobs:
  build-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

  build-fruit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ github.event.inputs.keyword }}!

  check-deploy:
    needs: [build-hello, build-fruit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check keyword
        run: bash validate-inputs-staging.sh ${{ github.event.inputs.keyword }}

  deploy-hello:
    needs: [check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo ${{ github.event.head_commit.message }}

  deploy-fruit:
    needs: [check-deploy]
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy ${{ github.event.inputs.keyword }}.
